In [1]:
x =[1,2,4,6,7,10,11]

In [2]:
import numpy as np

In [3]:
import numpy as np
def k_means_cluster(x,k=[3,3.9,8],iters=20):
    
    for _ in range(iters):
        p1, p2, p3= [],[],[]
        d=[0,0,0]
        for i in range(len(x)):
            for j in range(len(k)):
                d[j]=abs(x[i]-k[j])#for distance in absolute value

            mind=d.index(min(d)) #index of the minimum value in a list d.# Find which centroid is closest
            if mind==0:
                p1.append(x[i])
            if mind==1:
                p2.append(x[i])
            if mind==2:
                p3.append(x[i])
        k[0]= np.mean(p1)
        k[1]= np.mean(p2)
        k[2]= np.mean(p3)
    return k,p1,p2,p3

In [4]:
k,p1,p2,p3= k_means_cluster(x)


In [5]:
k

[1.5, 5.666666666666667, 10.5]

In [6]:
p1

[1, 2]

In [7]:
p2

[4, 6, 7]

In [8]:
p3

[10, 11]

In [9]:
X=np.array([[1,0],[1,1],[0,0]])
X

array([[1, 0],
       [1, 1],
       [0, 0]])

In [10]:
k=np.random.rand(1,3)
k

array([[0.03292719, 0.39838659, 0.40680587]])

In [18]:
def clusterM(X,K=3,iters=10):
    init_k = np.random.rand(K, X.shape[1])
    m=X.shape[0]
    v=[]
    for i in range(iters):
        v = np.zeros(m, dtype=int)
        for i, point in enumerate(X):
            distances = np.linalg.norm(point - init_k, axis=1)#for distance in absolute value
            v[i] = np.argmin(distances) # np.argmin() for array index smallest value 
            v=np.array(v)
        for i in range(K):#
            cluster_points = X[v == i]
            init_k[i] = np.mean(cluster_points, axis=0)

    return init_k, v    

In [45]:
clusterM(X,K=3,iters=10)

(array([[       nan,        nan],
        [0.66666667, 0.33333333],
        [       nan,        nan]]),
 array([1, 1, 1]))

In [54]:
k

array([[0.77756123, 0.93482061, 0.64101432]])

In [15]:
import pandas as pd
data = pd.read_csv("data/grades2.csv")

In [16]:
d_data = data[['grade1','grade2','result']]
d_data

grade1     grade2  result
0   34.623660  78.024693       0
1   30.286711  43.894998       0
2   35.847409  72.902198       0
3   60.182599  86.308552       1
4   79.032736  75.344376       1
5   45.083277  56.316372       0
6   61.106665  96.511426       1
7   75.024746  46.554014       1
8   84.432820  43.533393       1
9   75.013658  30.603263       0
10  82.307053  76.481963       1
11  39.538339  76.036811       0
12  69.070144  52.740470       1
13  67.946855  46.678574       0

In [19]:
clusterM(X,K=2,iters=10)

(array([[1. , 1. ],
        [0.5, 0. ]]),
 array([1, 0, 1]))